spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/kong
    password: 
    username: 
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: auth-service


server:
  port: 6666

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
